version: "3.7"

services:
  clean-todo-app-ui:
    container_name: clean-todo-app-ui
    build:
      context: .
      dockerfile: ./clean-todo-app-ui/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=Production
  clean-todo-app-api:
    container_name: clean-todo-app-api
    build:
      context: .
      dockerfile: ./clean-todo-app-api/CleanTodoApp.API/Dockerfile
